\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename user-manual
@settitle Radiology Information System User Manual
@c %**end of header

@copying
Radiology Information System User Manual

Created by Braeden Soetaert, Tyler Meen, Vincent Phung
@end copying

@titlepage
@title Radiology Information System User Manual
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of contents
@contents

@page

@ifnottex
@node Top
@top User Manual Menu
@uref{../../login/home.jsp,,Home Page}

This is a user manual for the Radiology Information System developed in the CMPUT 391 course.
@end ifnottex

@menu
* Login/Home:: Logging in and the Home page.
* User Management::    For Admins to manage users.
* Report Generation::  For Admins to generate reports of patients with a specific diagnosis for a specific time period.
* Uploading Images:: For Radiologists to upload images and create radiology records.
* Search:: Search system for radiology records and images relevant to you.
* Data Analysis:: For Admin to generate and display an OLAP report for data analysis
* Index::            Complete index.
@end menu

@node Login/Home 
@chapter Login/Home
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

Login to the system using your username and password. Once logged in, you will stay logged in unless you are inactive for 30 mins or more at a time. If you are inactive for this long you will have to log back in.

@menu
* Change Personal Info:: Change personal information.
* Home:: Home page.
* Login:: Logging in.
* Logout:: Logging out.
@end menu

@cindex Login Module

@node Change Personal Info 
@section Change Personal Info
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

You can change your personal info by clicking the ``Change Personal Info'' link in the navigation bar at the top of any page.

From this page you can change your personal password, address, email, and phone number. You can not change any of these pieces of information to be a blank value. If you submit a blank value for any piece of changeable information then the old value will be kept instead.

The reset button will reset the changeable information to their previous values. Once you press the submit button you will be displayed with a page that will update you about the status of your request to change information. If this page says your information was not successfully updated or that you did not submit any data please return to the change personal info page and try again.

@cindex Personal Info
@cindex Change Personal Info

@node Home 
@section Home
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

The home page displays your personal information for this current client session. You can use the links in the bar at the top of the page to navigate around the site. This home page is displayed upon first logging into the site and you will also be redirected to this homepage if you try to access another page that you do not have the correct permissions for.

@cindex Home Page

@node Login
@section Login
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

The login page will only allow you to login if you provide a valid username and password. Once you have logged in you will be logged out if you are inactive for 30 mins and you will be returned to this login page. Failed attempts will prompt the user to reenter their credentials.

@cindex Login

@node Logout
@section Logout
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

You can logout of the system by pressing the logout link in the navigation bar at the top of any page. Pressing this will log you out of the system and you will have to log back in via the login page. 

You will also be logged out and need to login again if you try to perform an action after having been inactive for 30 mins or more.
 
@cindex Logout

@node User Management
@chapter User Management
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

This module is broken into 3 different parts. There is a Edit Person section, Edit User section, and a Edit Family Doctor section. Only admin users have access to these sections.

@menu
* Edit Person:: Change person's info.
* Edit User:: Change user login information.
* Edit Family Doctor:: Change Doctor/Patient relationships.
@end menu

@cindex User Management Module
@cindex User Management

@node Edit Person
@section Edit Person
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

In this section you can edit the info in the Persons table. To add a new person the email address has to be unique, and the ID field has to be left blank. To edit an existing person, the ID needs to be filled with the ID of the person to edit. Any field left blank while editing an existing person will be filled in with the previous value that was in the table already. Removing an existing person requires that the ID field is filled in as well as the ID existing. If the ID is being used in one of the other tables, or is used as a radiology technician, the removal will fail.

@cindex Edit Person
@cindex Person, edit

@node Edit User
@section Edit User
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

This section is for editing the users table. When adding a new user, the User Name must be unique. The date fields are optional, if nothing is entered then the current date will be used. The password field and ID field need to be filled to add a new user, the ID field must match an ID in the person table. When edditing the User Name must be entered and match a User Name in the users table. If a user is a d or p and they are in the family doctor table, they can not be changed or deleted. When removing a user, the User Name field must be filled in. If a date is entered that does not exist, such as feb 31, it will instead be entered as march 2/3 depending on the year. It will add any extra days to the next month.

@cindex Edit User
@cindex User, edit

@node Edit Family Doctor
@section Edit Family Doctor
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

Edit Family Doctor: When adding a new entry to this table, the IDs must both exist in the persons table, and the docor ID must exist with a d class in the users table, and the patient ID must exist in the users table with a p class. There is no limit on deleting entries from this table.

@cindex Edit Family Doctor
@cindex Doctor, edit
@cindex Family Doctor, edit

@node Report Generation
@chapter Report Generation
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

This module can be used by an administrator to generate reports of patient's name, address, phone number and date diagnosed for a given time period and diagnosis. Only admins can access these pages. All other users will be redirected to the home page.

Only admins can access this page. All other users will be redirected to the home page if attempting to access this page.

@menu
* Request Diagnosis Report:: Enter request for report.
* Diagnosis Report Results:: Interpreting report results.
@end menu

@cindex Generate Reports
@cindex Report Generation

@node Request Diagnosis Report
@section Request Diagnosis Report
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

Request a diagnosis report by entering the beginning date from the drop down menus and the ending date from the drop down menus. Also select a diagnosis for which you want to see patients for. The diagnosis option of 'All Patients' will generate a report of all patients with a radiology test date inside the given range.

@cindex Request Diagnosis Report
@cindex Diagnosis Report, request

@node Diagnosis Report Results
@section Diagnosis Report Results
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

The report displays the entered parameters of begin/end time and diagnosis. If no data was obtained for the given parameters no data will be displayed and an error message will be displayed. Otherwise a table will be displayed containing each patient's first name, last name, address, phone, and the earliest date they were diagnosed with the givne diagnosis for the time fram specified.

For instance if John Doe was diagnosed with prostate cancer on both March 5th, 2013 and April 25th 2013 then a report with the time frame of 2013 for prostate cancer will only show the March 5th date. If the time frame is only April 2013 instead it will only show the April 25th date.

@cindex Diagnosis Report Results
@cindex Interpret Diagnosis Report

@node Uploading Images
@chapter Uploading Images
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

The Upload module allows the user to create records at the
top of the page and upload images into the individual records. In the creating page there is a form at top to allow for the creation of records. At the bottom of the page there is a table that shows each record that the radiologist has created. By clicking on the hyptertext located at each recordId the user is redirected to the upload image page. Here the radiologist can upload images into the record. 

@cindex Upload Module
@cindex Uploading Images

@node Search
@chapter Search
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

This module is used to search records that the current user has access to. The access rules are as follows: a patient can only view his/her own records; a doctor can only view records of their patients; a radiologist can only review records conducted by oneself; and an administrator can view any records. When entering info into the form you must enter atleast one date when sorting by date, and atleast one keyword when by sorting by ranking. If an end date is entered but no start date, then everything up untilt he end date will be selected. If no dates are entered for a ranking search then all no dates will be taken into account. If the start date is chosen without the end date, then everything after the start date will be selected. After the records have been searched the tables will be displayed at the bottom , with clickable thumbnails to view the pictures.

@cindex Search Module
@cindex Search

@node Data Analysis
@chapter Data Analysis
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

This module is used to run an analysis on the number of radiologist entries. When entering info into the form you must either enter a full date, or no date at all. This is for the start date as well as the end date. If an end date is entered but no start date, then everything up untilt he end date will be selected. If the start date is chosen without the end date, then everything after the start date will be selected. If a name is entered, both the first and last name need to be entered, and it is case sensitive. If nothing is ented then it will grab all patients and all tests for all time. Once the analysis is run, the user can choose to break it down by week, month or year.

@cindex Data Analysis Module
@cindex Data Analysis

@node Index
@unnumbered Index
@ifnottex
@uref{../../login/home.jsp,,Home Page}
@end ifnottex

@printindex cp

@bye
